const express=require('express');
const router=express.Router();
const Auth=require('../middleware/authorization');
const groupcontroller=require('../controllers/groupcontroller');
router.post('/add-group',Auth.authenticate,groupcontroller.addgroup);
router.get('/getgroup',Auth.authenticate,groupcontroller.getgroup);
router.post('/addusertogroup',Auth.authenticate,groupcontroller.addUserToGroup);
router.get('/groupuser',Auth.authenticate,groupcontroller.getUserOfGroup);
router.delete('/removeuser',Auth.authenticate,groupcontroller.removeUserFromGroup);
router.post('/makeuseradmin',Auth.authenticate,groupcontroller.makeUserAdmin);
module.exports=router;