const express=require('express');
const router=express.Router();
const Auth=require('../middlewares/authorization');
const Multer=require('../middlewares/multer');
const upload=Multer.multer.single('image');
const chatcontroller=require('../controllers/message-controller');
router.post('/send-message',Auth.authenticate,chatcontroller.sendMessage);
router.get('/get-message',Auth.authenticate,chatcontroller.getMessage);
router.post('/upload-file',Auth.authenticate,upload,chatcontroller.uploadfile);
module.exports=router;